<template>
  <div
    id="app"
    class="container"
  >
    <div class="app-login">
      <el-row
        type="flex"
        justify="center"
      >
        <el-form
          ref="loginForm"
          :model="User"
          :rules="rules"
          label-width="100px"
        >
          <h3>登录与注册</h3>
          <hr>
          <el-form-item
            label="用户名"
            prop="username"
          >
            <el-input
              v-model="User.username"
              placeholder="请输入用户名"
            />
          </el-form-item>

          <el-form-item
            label="密码"
            prop="password"
          >
            <el-input
              v-model="User.password"
              placeholder="请输入密码"
              type="password"
            />
          </el-form-item>
          <el-form-item>
            <el-button
              type="primary"
              @click="login('User')"
            >
              登录
            </el-button>
            <el-button @click="register('User')">
              注册
            </el-button>
            <!--                    <el-button type="success" @click="Admin('User')">管理员模式</el-button> -->
          </el-form-item>
        </el-form>
      </el-row>
    </div>
  </div>
</template>
